"""Linker Tables

Revision ID: 64253239b326
Revises: 095a740dd6bc
Create Date: 2018-06-04 14:29:55.184947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64253239b326'
down_revision = '095a740dd6bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_token', sa.String(length=255), nullable=True),
    sa.Column('wallet_token', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=255), nullable=True),
    sa.Column('code_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_rpc', sa.String(length=255), nullable=True),
    sa.Column('current_accounts', sa.JSON(), nullable=True),
    sa.Column('pending_call', sa.JSON(), nullable=True),
    sa.Column('current_return_url', sa.String(length=255), nullable=True),
    sa.Column('linked', sa.Boolean(), nullable=True),
    sa.Column('app_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linked_tokens_client_token'), 'linked_tokens', ['client_token'], unique=False)
    op.create_index(op.f('ix_linked_tokens_code'), 'linked_tokens', ['code'], unique=False)
    op.create_index(op.f('ix_linked_tokens_current_rpc'), 'linked_tokens', ['current_rpc'], unique=False)
    op.create_index(op.f('ix_linked_tokens_wallet_token'), 'linked_tokens', ['wallet_token'], unique=False)
    op.create_table('wallet_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_token', sa.String(length=255), nullable=True),
    sa.Column('current_accounts', sa.String(length=255), nullable=True),
    sa.Column('type', sa.Enum('NETWORK', 'ACCOUNTS', 'CALL', 'CALL_RESPONSE', 'LOGOUT', name='messagetypes'), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_message_wallet_token'), 'wallet_message', ['wallet_token'], unique=False)
    op.create_table('linked_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=True),
    sa.Column('linked_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['linked_id'], ['linked_tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('linked_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('NETWORK', 'ACCOUNTS', 'CALL', 'CALL_RESPONSE', 'LOGOUT', name='messagetypes'), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['linked_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('linked_message')
    op.drop_table('linked_session')
    op.drop_index(op.f('ix_wallet_message_wallet_token'), table_name='wallet_message')
    op.drop_table('wallet_message')
    op.drop_index(op.f('ix_linked_tokens_wallet_token'), table_name='linked_tokens')
    op.drop_index(op.f('ix_linked_tokens_current_rpc'), table_name='linked_tokens')
    op.drop_index(op.f('ix_linked_tokens_code'), table_name='linked_tokens')
    op.drop_index(op.f('ix_linked_tokens_client_token'), table_name='linked_tokens')
    op.drop_table('linked_tokens')
    # ### end Alembic commands ###
