"""empty message

Revision ID: 8e4e4ff24109
Revises: 64253239b326
Create Date: 2018-07-12 15:35:44.033545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e4e4ff24109'
down_revision = '64253239b326'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linked_tokens', sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('linked_tokens', 'linked_at')
    # ### end Alembic commands ###
